[package]
name = "rubigo"
version = "0.0.9"
authors = ["Blinningjr <inaule-6@student.ltu.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
